version: '2'
services:
  piano_js:
    container_name: piano-js
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
     - npm-network

networks:
  npm-network:
    external: true

