name: publish-ci
on:
  push:
    branches: ['recordless-piano']
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Login to GitHub Package Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          
      - name: Build piano js Docker image
        run: |
          docker build . --tag ghcr.io/omarmelade/piano-js-recordless
          docker push ghcr.io/omarmelade/piano-js-recordless:latest
