name: Auto deploy

on:
  push:
    branches: [ recordless-piano ]
  pull_request:
    branches: [ recordless-piano ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build & Deploy the Docker image
      run: >-
        docker-compose up --build --force-recreate --no-deps --detach 
        && docker image prune -f
