name: Auto deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Build & Deploy the Docker image
      run: docker-compose up build --force-recreate --no-deps --no-cache -d && docker-compose up -d && docker image prune -f
